databases:
  - name: kefi
    databaseName: kefi
    user: kefi_user

services:
  - type: web
    name: kefi-hotel
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kefi
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
