databases:
  - name: kefi-backend
    databaseName: kefi_backend
    user: kefi_backend_user

services:
  - type: web
    name: Kefi-Hotel-Booking-App
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kefi_backend
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
